version: "3.7"
services:
  app:
    build:
      args:
        user: eli
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tracker-app
    container_name: tracker-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tracker-app

  db:
    image: mysql:5.7
    container_name: tracker-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3388:3306"
    networks:
      - tracker-app

  nginx:
    image: nginx:alpine
    container_name: tracker-app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - tracker-app

networks:
  tracker-app:
    driver: bridge
